2022-02-19 09:33:52,221 INFO    MainThread:13032 [wandb_setup.py:_flush():75] Loading settings from C:\Users\alexd\.config\wandb\settings
2022-02-19 09:33:52,221 INFO    MainThread:13032 [wandb_setup.py:_flush():75] Loading settings from C:\Users\alexd\OneDrive\Documents\AIDL\Winter Semester\AIDL_B_02\Assignment\Anime Faces and Names\wandb\settings
2022-02-19 09:33:52,221 INFO    MainThread:13032 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-19 09:33:52,221 INFO    MainThread:13032 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-19 09:33:52,222 INFO    MainThread:13032 [wandb_init.py:_log_setup():386] Logging user logs to C:\Users\alexd\OneDrive\Documents\AIDL\Winter Semester\AIDL_B_02\Assignment\Anime Faces and Names\wandb\run-20220219_093352-17p6rwnp\logs\debug.log
2022-02-19 09:33:52,222 INFO    MainThread:13032 [wandb_init.py:_log_setup():387] Logging internal logs to C:\Users\alexd\OneDrive\Documents\AIDL\Winter Semester\AIDL_B_02\Assignment\Anime Faces and Names\wandb\run-20220219_093352-17p6rwnp\logs\debug-internal.log
2022-02-19 09:33:52,222 INFO    MainThread:13032 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000245C116C160>
2022-02-19 09:33:52,222 INFO    MainThread:13032 [wandb_init.py:init():420] calling init triggers
2022-02-19 09:33:52,222 INFO    MainThread:13032 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-19 09:33:52,222 INFO    MainThread:13032 [wandb_init.py:init():441] re-initializing run, found existing run on stack: eh9n1jf4
2022-02-19 09:33:52,224 INFO    MainThread:13032 [wandb_run.py:finish():1468] finishing run skycladai/Anime Creation/eh9n1jf4
2022-02-19 09:33:52,224 INFO    MainThread:13032 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-19 09:33:52,225 INFO    MainThread:13032 [wandb_run.py:_restore():1769] restore
2022-02-19 09:33:52,745 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 755
  total_bytes: 755
}

2022-02-19 09:33:53,034 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 755
  total_bytes: 755
}

2022-02-19 09:33:54,060 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 755
  total_bytes: 4603
}

2022-02-19 09:33:54,166 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 755
  total_bytes: 4603
}

2022-02-19 09:33:54,277 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 755
  total_bytes: 4603
}

2022-02-19 09:33:54,387 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 755
  total_bytes: 4603
}

2022-02-19 09:33:54,498 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:54,606 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:54,716 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:54,824 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:54,928 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:55,038 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:55,721 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}

2022-02-19 09:33:56,358 INFO    MainThread:13032 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4603
  total_bytes: 4603
}
local_info {
}

2022-02-19 09:33:57,665 INFO    MainThread:13032 [wandb_run.py:_append_files():2194] logging synced files
2022-02-19 09:33:57,670 INFO    MainThread:13032 [wandb_init.py:init():471] starting backend
2022-02-19 09:33:57,670 INFO    MainThread:13032 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-02-19 09:33:57,672 INFO    MainThread:13032 [backend.py:ensure_launched():219] starting backend process...
2022-02-19 09:33:57,744 INFO    MainThread:13032 [backend.py:ensure_launched():224] started backend process with pid: 1852
2022-02-19 09:33:57,745 INFO    MainThread:13032 [wandb_init.py:init():480] backend started and connected
2022-02-19 09:33:57,747 INFO    MainThread:13032 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-19 09:33:57,747 INFO    MainThread:13032 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-19 09:33:57,747 INFO    MainThread:13032 [wandb_init.py:init():550] updated telemetry
2022-02-19 09:33:57,751 INFO    MainThread:13032 [wandb_init.py:init():581] communicating current version
2022-02-19 09:33:59,242 INFO    MainThread:13032 [wandb_init.py:init():586] got version response 
2022-02-19 09:33:59,242 INFO    MainThread:13032 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-19 09:33:59,580 INFO    MainThread:13032 [wandb_init.py:init():624] starting run threads in backend
2022-02-19 09:34:02,162 INFO    MainThread:13032 [wandb_run.py:_console_start():1827] atexit reg
2022-02-19 09:34:02,163 INFO    MainThread:13032 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-19 09:34:02,163 INFO    MainThread:13032 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-19 09:34:02,166 INFO    MainThread:13032 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-19 09:34:02,166 INFO    MainThread:13032 [wandb_init.py:init():651] run started, returning control to user process
2022-02-19 09:34:02,169 INFO    MainThread:13032 [wandb_init.py:_pause_backend():299] pausing backend
2022-02-19 09:34:02,169 INFO    MainThread:13032 [jupyter.py:save_ipynb():377] looking for notebook: OneDrive/Documents/AIDL/Winter Semester/AIDL_B_02/Assignment/Anime Faces and Names/anime creation.ipynb
2022-02-19 09:34:11,653 INFO    MainThread:13032 [wandb_init.py:_resume_backend():308] resuming backend
2022-02-19 09:34:11,673 INFO    MainThread:13032 [wandb_init.py:_pause_backend():299] pausing backend
2022-02-19 09:34:11,673 INFO    MainThread:13032 [jupyter.py:save_ipynb():377] looking for notebook: OneDrive/Documents/AIDL/Winter Semester/AIDL_B_02/Assignment/Anime Faces and Names/anime creation.ipynb
